version: "3.2"
services:

  redis:
    image: "redis:alpine"
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - redis

    ports:
      - 6379:6379

  redis-insgiht:
    image: "redislabs/redisinsight:latest"
    volumes:
      - redisinsight:/db
    ports:
      - 8001:8001

    networks:
      - redis

volumes:
  redis-data:
  redisinsight:

networks:
  redis: