name: Execute checks on PR

on:
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  push:
    branches: [main]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Check formatting with Black
        run: black --check src tests

      - name: Check code against Flake8
        run: flake8 src tests

      - name: Perform type check with MyPy
        run: mypy --ignore-missing-imports .

      - name: Fail if any of the checks fail
        run: |
          if [ ${{ steps.check-black.outcome }} == "failure" ] || [ ${{ steps.check-flake8.outcome }} == "failure" ] || [ ${{ steps.check-mypy.outcome }} == "failure" ]; then exit 1; fi

  pytest-unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Run Pytest Unittests only
        run: pytest --unittest --runslow

      - name: Run Pytest Intrgration without DB
        run: pytest --integration=nodb --runslow

  pytest-docker-redis:
    runs-on: ubuntu-latest
    services:
      redis:
        image: "redis:alpine"
        options: "redis-server"
        env:
          REDIS_REPLICATION_MODE: master
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Run Pytest Redis only
        run: pytest --integration=redis --runslow

  pytest-docker-mongo:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: toor
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[tests]

      - name: Run Pytest MongoDB only
        run: pytest --integration=mongo --runslow
